name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate --schema=../../packages/database/prisma/schema.prisma"
dev = "pnpm exec react-router dev"
